import { apiRequest } from './client';
export type Page<T> = { rows: T[]; pagination: { page: number; limit: number; total: number; totalPages: number } };
export type Product = { id: number; product_name: string; sku: string; category: string; unit_price: number; current_stock: number; minimum_stock_quantity: number; warehouse_location: string; updated_at?: string };
export type Movement = { id: number; product_id: number; product_name: string; sku: string; quantity_changed: number; movement_type: 'IN' | 'OUT'; reason: string; created_by_name: string; created_at: string };
export type Customer = { id: number; customer_name: string; mobile: string; email?: string; business_name: string; gst_number?: string; customer_type: string; address: string; status: string; follow_up_date?: string; notes?: string };
export type Challan = { id: number; challan_number: string; customer_id: number; business_name: string; customer_name: string; total_quantity: number; status: 'DRAFT' | 'CONFIRMED' | 'CANCELLED'; created_by_name: string; created_at: string };
const query = (params: Record<string, string | number | boolean | undefined>) => { const entries = Object.entries(params).filter(([, v]) => v !== undefined && v !== ''); return entries.length ? `?${new URLSearchParams(entries.map(([k, v]) => [k, String(v)]))}` : ''; };
export const erpApi = {
 dashboard: { summary: () => apiRequest<any>('/dashboard/summary'), inventory: () => apiRequest<any>('/dashboard/inventory'), challans: () => apiRequest<any>('/dashboard/challans'), activity: (from?: string, to?: string) => apiRequest<any>(`/dashboard/activity${query({ from, to })}`) },
 products: { list: (p: Record<string, string | number | boolean | undefined>) => apiRequest<Page<Product>>(`/products${query(p)}`), get: (id: number) => apiRequest<Product>(`/products/${id}`), create: (b: Partial<Product>) => apiRequest<Product>('/products', { method: 'POST', body: JSON.stringify(b) }), update: (id: number, b: Partial<Product>) => apiRequest<Product>(`/products/${id}`, { method: 'PUT', body: JSON.stringify(b) }), stock: (id: number, type: 'in' | 'out', b: { quantity: number; reason: string }) => apiRequest<Product>(`/products/${id}/stock/${type}`, { method: 'POST', body: JSON.stringify(b) }) },
 movements: (p: Record<string, string | number | undefined> = {}) => apiRequest<Page<Movement>>(`/stock-movements${query(p)}`),
 customers: { list: (p: Record<string, string | number | undefined>) => apiRequest<Page<Customer>>(`/customers${query(p)}`), create: (b: Partial<Customer>) => apiRequest<Customer>('/customers', { method: 'POST', body: JSON.stringify(b) }), followUps: (id: number) => apiRequest<any[]>(`/customers/${id}/follow-ups`), addFollowUp: (id: number, b: { follow_up_date: string; note: string }) => apiRequest<any>(`/customers/${id}/follow-ups`, { method: 'POST', body: JSON.stringify(b) }) },
 challans: { list: (p: Record<string, string | number | undefined>) => apiRequest<Page<Challan>>(`/challans${query(p)}`), get: (id: number) => apiRequest<any>(`/challans/${id}`), create: (b: { customerId: number; items: { productId: number; quantity: number }[] }) => apiRequest<any>('/challans', { method: 'POST', body: JSON.stringify(b) }), update: (id: number, b: { customerId: number; items: { productId: number; quantity: number }[] }) => apiRequest<any>(`/challans/${id}`, { method: 'PUT', body: JSON.stringify(b) }), confirm: (id: number) => apiRequest<any>(`/challans/${id}/confirm`, { method: 'POST' }), cancel: (id: number) => apiRequest<any>(`/challans/${id}/cancel`, { method: 'POST' }) }
};
